[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[redirects]]
  from = "http://danielelolli.it/*"
  to = "https://www.uncledan.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://www.danielelolli.it/*"
  to = "https://www.uncledan.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://danielelolli.it/*"
  to = "https://www.uncledan.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.danielelolli.it/*"
  to = "https://www.uncledan.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https:/uncledan.netlify.app/*"
  to = "https://www.uncledan.it/:splat"
  status = 301
  force = true