[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[redirects]]
  from = "http://zfurdesign.it/*"
  to = "https://www.zabinifur.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://www.zfurdesign.it/*"
  to = "https://www.zabinifur.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://zfurdesign.it/*"
  to = "https://www.zabinifur.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://zfurdesign.netlify.app/*"
  to = "https://www.zabinifur.it/:splat"
  status = 301
  force = true