[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[redirects]]
  from = "http://uncledan.it/*"
  to = "https://www.danielelolli.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://www.uncledan.it/*"
  to = "https://www.danielelolli.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://uncledan.it/*"
  to = "https://www.danielelolli.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.uncledan.it/*"
  to = "https://www.danielelolli.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www-uncledan-it.netlify.app/*"
  to = "https://www.danielelolli.it/:splat"
  status = 301
  force = true