[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[redirects]]
  from = "http://lolli.cloud/*"
  to = "https://www.danielelolli.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://www.lolli.cloud/*"
  to = "https://www.danielelolli.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://lolli.cloud/*"
  to = "https://www.danielelolli.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www-lolli-cloud.netlify.app/*"
  to = "https://www.danielelolli.it/:splat"
  status = 301
  force = true